spring:
  application:
    name: order
  data:
    mongodb:
      database: order
      host: ${DB_HOST:localhost}

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
---
spring:
  profiles: docker
  data:
    mongodb:
      database: order
      host: orderdb

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/